### ISSUE TITLE
nexus is failing to get IP after reboot : IP_DROP_MEMBERSHIP failed: Can't assign requested address 

### ISSUE THREAD

**Issue by AlbanAndrieu** [rebasing-xyz/iocage-nexus-oss#18]
nexus plugin installation is working, but after reboot (or restart of plugin) service is unavailable at http://192.168.132.24:8081/

Feb 16 10:33:09 nabla kernel: lo0: link state changed to UP
Feb 16 10:33:13 nabla 1 2022-02-16T10:33:13.300243+01:00 nabla.albandrieu.com avahi-daemon 90550 - - IP_DROP_MEMBERSHIP failed: Can't assign requested address
Feb 16 10:33:52 nabla 1 2022-02-16T10:33:52.549237+01:00 nabla.albandrieu.com ctld 1294 - - connect(2) failed for 192.168.132.57: Connection refused

I'am using : version: TrueNAS-12.0-U8

**Comment by AlbanAndrieu** [comment]
Suspecting service not to start at boot time.
If you can access jail shell :
service nexus start

**Comment by micle546** [comment]
same issue. Nexus service doesn't seem to restart after jail gets restarted,
"service nexus start" seems to fix it

**Comment by spolti** [comment]
Hi @AlbanAndrieu and @micle546, thanks very much for reporting it. 
I'll take a look on this in the upcoming days. will keep you posted.

Thanks.

**Comment by spolti** [comment]
Hi issue should be fixed by now, a fresh plugin install might be required, or apply the same steps on the commit referenced here.
